# Generated by Django 3.0.3 on 2020-02-26 18:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0002_auto_20200226_2004'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Artticle',
            new_name='Article',
        ),
    ]
